[workspace]
# Let github create the notes for each release
git_release_generate_notes=true
git_release_body=""
# Only release on release PR merge
release_always=true

# Temp fix until booru-rs 2.0 is released to crates
# Reason is that git dependencies can't be uploaded to crates.io
publish=false
git_only=true
